<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.hasor</groupId>
        <artifactId>hasor-parent</artifactId>
        <version>5.0.0</version>
    </parent>

    <!-- Maven Info -->
    <artifactId>hasor-boot</artifactId>
    <packaging>pom</packaging>

    <!-- Project Info -->
    <name>Hasor-Boot</name>
    <description>Hasor executable archive packaging and runtime launcher.</description>

    <modules>
        <module>hasor-boot-loader</module>
        <module>hasor-boot-maven-plugin</module>
        <module>hasor-boot-gradle-plugin</module>
        <module>hasor-boot-tomcat</module>
        <module>hasor-boot-jetty</module>
        <module>hasor-boot-undertow</module>
    </modules>
</project>
