pluginManagement {
    includeBuild 'hasor-boot/hasor-boot-gradle-plugin'

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

rootProject.name = 'hasor-parent'

include 'hasor-core'
include 'hasor-web'
include 'hasor-config'
include 'hasor-boot-loader'
include 'hasor-boot-web'
include 'hasor-boot-maven-plugin'
include 'hasor-boot-web-tomcat'
include 'hasor-boot-web-jetty'
include 'hasor-boot-web-undertow'
include 'test-web-containers'

project(':hasor-boot-loader').projectDir = file('hasor-boot/hasor-boot-loader')
project(':hasor-boot-web').projectDir = file('hasor-boot/hasor-boot-web')
project(':hasor-boot-maven-plugin').projectDir = file('hasor-boot/hasor-boot-maven-plugin')
project(':hasor-boot-web-tomcat').projectDir = file('hasor-boot/hasor-boot-web-tomcat')
project(':hasor-boot-web-jetty').projectDir = file('hasor-boot/hasor-boot-web-jetty')
project(':hasor-boot-web-undertow').projectDir = file('hasor-boot/hasor-boot-web-undertow')
project(':test-web-containers').projectDir = file('hasor-boot/test-web-containers')
