plugins {
    id 'java-library'
    id 'maven-publish'
}

configurations {
    shaded
}

dependencies {
    api "org.slf4j:slf4j-api:${property('lib.slf4j')}"
    api "net.hasor:cobble-all:${property('lib.cobble')}"
    shaded "javax.inject:javax.inject:${property('lib.inject')}"

    compileOnly "javax.annotation:javax.annotation-api:${property('lib.annotation')}"
    compileOnly "javax.inject:javax.inject:${property('lib.inject')}"
}

tasks.named('jar') {
    from { configurations.shaded.collect { it.isDirectory() ? it : zipTree(it) } }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
